package cz.valkovic.twbot.modules.parsing.locations;

import cz.valkovic.twbot.modules.core.pipeping.PIPES;
import cz.valkovic.twbot.modules.core.pipeping.PipesRegistrationService;
import cz.valkovic.twbot.modules.parsing.LOCATIONS;
import cz.valkovic.twbot.modules.parsing.locations.messages.MessageReadLocPipe;
import cz.valkovic.twbot.modules.parsing.locations.messages.MessagesLocPipe;
import cz.valkovic.twbot.modules.parsing.locations.reports.*;
import cz.valkovic.twbot.modules.parsing.locations.stats.*;
import cz.valkovic.twbot.modules.parsing.locations.tribe.*;
import cz.valkovic.twbot.modules.parsing.locations.village.*;
import cz.valkovic.twbot.modules.parsing.locations.wordpriperties.InterfaceBuildingsLocPipe;
import cz.valkovic.twbot.modules.parsing.locations.wordpriperties.InterfaceConfigLocPipe;
import cz.valkovic.twbot.modules.parsing.locations.wordpriperties.InterfaceLocPipe;
import cz.valkovic.twbot.modules.parsing.locations.wordpriperties.InterfaceUnitsLocPipe;
import javax.inject.Inject;

public class LocationPipesRegistration {

    @Inject
    public static void register(PipesRegistrationService pipes){

        pipes.registerLocationPipe(
                PIPES.EVERYTHING.toString(),
                LOCATIONS.APPLICATION.toString(),
                ApplicationLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.APPLICATION.toString(),
                LOCATIONS.INGAME.toString(),
                IngameLocPipe.class
        );

        pipes.registerLocationPipe(
                LOCATIONS.APPLICATION.toString(),
                LOCATIONS.LOGIN.toString(),
                LoginLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.APPLICATION.toString(),
                LOCATIONS.SERVER_PICKUP.toString(),
                ServerPickupLocPipe.class
        );

        //region interface
        pipes.registerLocationPipe(
                LOCATIONS.INGAME.toString(),
                LOCATIONS.INTERFACE.toString(),
                InterfaceLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.INTERFACE.toString(),
                LOCATIONS.INTERFACE_CONFIG.toString(),
                InterfaceConfigLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.INTERFACE.toString(),
                LOCATIONS.INTERFACE_BUILDINGS.toString(),
                InterfaceBuildingsLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.INTERFACE.toString(),
                LOCATIONS.INTERFACE_UNITS.toString(),
                InterfaceUnitsLocPipe.class
        );
        //endregion

        //region stats
        pipes.registerLocationPipe(
                LOCATIONS.INGAME.toString(),
                LOCATIONS.STATS.toString(),
                StatsLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.STATS.toString(),
                LOCATIONS.STATS_VILLAGES.toString(),
                StatsVillagesLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.STATS.toString(),
                LOCATIONS.STATS_PLAYERS.toString(),
                StatsPlayersLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.STATS.toString(),
                LOCATIONS.STATS_TRIBES.toString(),
                StatsTribesLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.STATS.toString(),
                LOCATIONS.STATS_KILLALL.toString(),
                StatsKillAllLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.STATS.toString(),
                LOCATIONS.STATS_ATT.toString(),
                StatsAttLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.STATS.toString(),
                LOCATIONS.STATS_DEF.toString(),
                StatsDefLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.STATS.toString(),
                LOCATIONS.STATS_TRIBE_ALL.toString(),
                StatsTribeAllLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.STATS.toString(),
                LOCATIONS.STATS_TRIBE_ATT.toString(),
                StatsTribeAttLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.STATS.toString(),
                LOCATIONS.STATS_TRIBE_DEF.toString(),
                StatsTribeDefLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.STATS.toString(),
                LOCATIONS.STATS_CONQUER.toString(),
                StatsConquerLocPipe.class
        );
        //endregion

        //region ingame
        pipes.registerLocationPipe(
                LOCATIONS.INGAME.toString(),
                LOCATIONS.DASHBOARD.toString(),
                DashboardLocPipe.class
        );
        //region messages
        pipes.registerLocationPipe(
                LOCATIONS.INGAME.toString(),
                LOCATIONS.MESSAGES.toString(),
                MessagesLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.INGAME.toString(),
                LOCATIONS.MESSAGE_READ.toString(),
                MessageReadLocPipe.class
        );
        //endregion
        //region village
        pipes.registerLocationPipe(
                LOCATIONS.INGAME.toString(),
                LOCATIONS.VILLAGE.toString(),
                VillageLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.VILLAGE.toString(),
                LOCATIONS.VILLAGE_OVERVIEW.toString(),
                VillageOverviewLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.VILLAGE.toString(),
                LOCATIONS.VILLAGE_HEADQUARTER.toString(),
                VillageHeadquarterLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.VILLAGE.toString(),
                LOCATIONS.VILLAGE_BARRACKS.toString(),
                VillageBarracksLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.VILLAGE.toString(),
                LOCATIONS.VILLAGE_STABLE.toString(),
                VillageStableLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.VILLAGE.toString(),
                LOCATIONS.VILLAGE_WORKSHOP.toString(),
                VillageWorkshopLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.VILLAGE.toString(),
                LOCATIONS.VILLAGE_ACADEMY.toString(),
                VillageAcademyLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.VILLAGE.toString(),
                LOCATIONS.VILLAGE_SMITHY.toString(),
                VillageSmithyLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.VILLAGE.toString(),
                LOCATIONS.VILLAGE_RALLYPOINT.toString(),
                VillageRallypointLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.VILLAGE_RALLYPOINT.toString(),
                LOCATIONS.VILLAGE_RALLYPOINT_COMMANDS.toString(),
                VillageRallypointCommandsLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.VILLAGE_RALLYPOINT.toString(),
                LOCATIONS.VILLAGE_RALLYPOINT_UNITS.toString(),
                VillageRallypointUnitsLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.VILLAGE_RALLYPOINT.toString(),
                LOCATIONS.VILLAGE_RALLYPOINT_SCAVENGE.toString(),
                VillageRallypointScavengeLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.VILLAGE_RALLYPOINT.toString(),
                LOCATIONS.VILLAGE_RALLYPOINT_MASSSCAVENGE.toString(),
                VillageRallypointMassscavengeLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.VILLAGE_RALLYPOINT.toString(),
                LOCATIONS.VILLAGE_RALLYPOINT_SIMULATOR.toString(),
                VillageRallypointSimulatorLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.VILLAGE_RALLYPOINT.toString(),
                LOCATIONS.VILLAGE_RALLYPOINT_TEMPLATES.toString(),
                VillageRallypointTemplatesLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.VILLAGE.toString(),
                LOCATIONS.VILLAGE_STATUE.toString(),
                VillageStatueLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.VILLAGE_STATUE.toString(),
                LOCATIONS.VILLAGE_STATUE_CURRENT.toString(),
                VillageStatueCurrentLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.VILLAGE_STATUE.toString(),
                LOCATIONS.VILLAGE_STATUE_OVERVIEW.toString(),
                VillageStatueOverviewLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.VILLAGE.toString(),
                LOCATIONS.VILLAGE_MARKET.toString(),
                VillageMarketLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.VILLAGE_MARKET.toString(),
                LOCATIONS.VILLAGE_MARKET_EXCHANGE.toString(),
                VillageMarketExchangeLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.VILLAGE_MARKET.toString(),
                LOCATIONS.VILLAGE_MARKET_PREMIUMEXCHANGE.toString(),
                VillageMarketPremiumExchangeLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.VILLAGE_MARKET.toString(),
                LOCATIONS.VILLAGE_MARKET_OFFERCREATE.toString(),
                VillageMarketOfferCreateLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.VILLAGE_MARKET.toString(),
                LOCATIONS.VILLAGE_MARKET_SEND.toString(),
                VillageMarketSendLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.VILLAGE_MARKET.toString(),
                LOCATIONS.VILLAGE_MARKET_TRANSPORTS.toString(),
                VillageMarketTransportsLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.VILLAGE_MARKET.toString(),
                LOCATIONS.VILLAGE_MARKET_STATUS.toString(),
                VillageMarketStatusLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.VILLAGE_MARKET.toString(),
                LOCATIONS.VILLAGE_MARKET_OFFERS.toString(),
                VillageMarketOffersLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.VILLAGE.toString(),
                LOCATIONS.VILLAGE_WOOD.toString(),
                VillageWoodLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.VILLAGE.toString(),
                LOCATIONS.VILLAGE_CLAY.toString(),
                VillageClayLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.VILLAGE.toString(),
                LOCATIONS.VILLAGE_IRON.toString(),
                VillageIronLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.VILLAGE.toString(),
                LOCATIONS.VILLAGE_FARM.toString(),
                VillageFarmLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.VILLAGE.toString(),
                LOCATIONS.VILLAGE_WAREHOUSE.toString(),
                VillageWarehouseLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.VILLAGE.toString(),
                LOCATIONS.VILLAGE_HIDEOUT.toString(),
                VillageHideoutLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.VILLAGE.toString(),
                LOCATIONS.VILLAGE_WALL.toString(),
                VillageWallLocPipe.class
        );
        //endregion
        //region reports
        pipes.registerLocationPipe(
                LOCATIONS.INGAME.toString(),
                LOCATIONS.REPORTS.toString(),
                ReportsLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.REPORTS.toString(),
                LOCATIONS.REPORTS_ALL.toString(),
                ReportsAllLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.REPORTS.toString(),
                LOCATIONS.REPORTS_ATT.toString(),
                ReportsAttLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.REPORTS.toString(),
                LOCATIONS.REPORTS_DEF.toString(),
                ReportsDefLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.REPORTS.toString(),
                LOCATIONS.REPORTS_SUPPORT.toString(),
                ReportsSupportLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.REPORTS.toString(),
                LOCATIONS.REPORTS_TRADE.toString(),
                ReportsTradeLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.REPORTS.toString(),
                LOCATIONS.REPORTS_EVENTS.toString(),
                ReportsEventsLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.REPORTS.toString(),
                LOCATIONS.REPORTS_OTHER.toString(),
                ReportsOtherLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.REPORTS.toString(),
                LOCATIONS.REPORTS_FORWARD.toString(),
                ReportsForwardLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.REPORTS.toString(),
                LOCATIONS.REPORTS_PUBLIC.toString(),
                ReportsPublicLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.REPORTS.toString(),
                LOCATIONS.REPORTS_FILTER.toString(),
                ReportsFilterLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.REPORTS.toString(),
                LOCATIONS.REPORT_READ.toString(),
                ReportReadLocPipe.class
        );
        //endregion
        pipes.registerLocationPipe(
                LOCATIONS.INGAME.toString(),
                LOCATIONS.MAP.toString(),
                MapLocPipe.class
        );
        //region TRIBE
        pipes.registerLocationPipe(
                LOCATIONS.INGAME.toString(),
                LOCATIONS.TRIBE.toString(),
                TribeLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.TRIBE.toString(),
                LOCATIONS.TRIBE_OVERVIEW.toString(),
                TribeOverviewLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.TRIBE.toString(),
                LOCATIONS.TRIBE_PROPERTIES.toString(),
                TribePropertiesLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.TRIBE.toString(),
                LOCATIONS.TRIBE_LEVEL.toString(),
                TribeLevelLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.TRIBE.toString(),
                LOCATIONS.TRIBE_MEMBERS.toString(),
                TribeMembersLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.TRIBE.toString(),
                LOCATIONS.TRIBE_DIPLOMACY.toString(),
                TribeDiplomacyLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.TRIBE.toString(),
                LOCATIONS.TRIBE_RESERVATIONS.toString(),
                TribeReservationsLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.TRIBE.toString(),
                LOCATIONS.TRIBE_RECRUIT.toString(),
                TribeRectuitLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.INGAME.toString(),
                LOCATIONS.TRIBE_WARS.toString(),
                WarsLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.TRIBE_WARS.toString(),
                LOCATIONS.TRIBE_WARS_CURRENT.toString(),
                WarsCurrentLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.TRIBE_WARS.toString(),
                LOCATIONS.TRIBE_WARS_INVITES.toString(),
                WarsInvitesLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.TRIBE_WARS.toString(),
                LOCATIONS.TRIBE_WARS_DECLARATION.toString(),
                WarsDeclarationLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.TRIBE_WARS.toString(),
                LOCATIONS.TRIBE_WARS_ARCHIVE.toString(),
                WarsArchiveLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.TRIBE_WARS.toString(),
                LOCATIONS.TRIBE_WARS_SCORE.toString(),
                WarsScoreLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.TRIBE_WARS.toString(),
                LOCATIONS.TRIBE_WARS_CURRENT.toString(),
                WarsCurrentLocPipe.class
        );
        //endregion
        //region forum
        pipes.registerLocationPipe(
                LOCATIONS.INGAME.toString(),
                LOCATIONS.FORUM.toString(),
                ForumLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.FORUM.toString(),
                LOCATIONS.FORUM_SECTION.toString(),
                ForumSectionLocPipe.class
        );
        pipes.registerLocationPipe(
                LOCATIONS.FORUM.toString(),
                LOCATIONS.FORUM_THREAD.toString(),
                ForumThreadLocPipe.class
        );
        //endregion
        //endregion
    }

}
